# fmt: off
# flake8: noqa
"""
This file declares the C-API corresponding to metatensor.h, in a way compatible
with the ctypes Python module.

This file is automatically generated by `scripts/update-declarations.py`,
do not edit it manually!
"""

import ctypes
import platform
from ctypes import CFUNCTYPE, POINTER


class EnumType(type(ctypes.c_int32)):
    def __new__(metacls, name, bases, dict):
        if "_members_" not in dict:
            _members_ = {}
            for key, value in dict.items():
                if not key.startswith("_"):
                    _members_[key] = value

            dict["_members_"] = _members_
        else:
            _members_ = dict["_members_"]

        dict["_reverse_map_"] = {v: k for k, v in _members_.items()}
        cls = type(ctypes.c_int32).__new__(metacls, name, bases, dict)
        for key, value in cls._members_.items():
            globals()[key] = value
        return cls

    def __repr__(self):
        return "<Enum %s>" % self.__name__


class Enum(ctypes.c_int32, metaclass=EnumType):
    _members_ = {}

    def __repr__(self):
        value_str = self._reverse_map_.get(self.value, str(self.value))
        return f"{self.__class__.__name__}.{value_str}"

    def __eq__(self, other):
        if isinstance(other, int):
            return self.value == other

        return type(self) is type(other) and self.value == other.value


arch = platform.architecture()[0]
if arch == "32bit":
    c_uintptr_t = ctypes.c_uint32
elif arch == "64bit":
    c_uintptr_t = ctypes.c_uint64



class DLDeviceType(Enum):
    kDLCPU = 1
    kDLCUDA = 2
    kDLCUDAHost = 3
    kDLOpenCL = 4
    kDLVulkan = 7
    kDLMetal = 8
    kDLVPI = 9
    kDLROCM = 10
    kDLROCMHost = 11
    kDLExtDev = 12
    kDLCUDAManaged = 13
    kDLOneAPI = 14
    kDLWebGPU = 15
    kDLHexagon = 16
    kDLMAIA = 17
    kDLTrn = 18


class DLDataTypeCode(Enum):
    kDLInt = 0
    kDLUInt = 1
    kDLFloat = 2
    kDLOpaqueHandle = 3
    kDLBfloat = 4
    kDLComplex = 5
    kDLBool = 6
    kDLFloat8_e3m4 = 7
    kDLFloat8_e4m3 = 8
    kDLFloat8_e4m3b11fnuz = 9
    kDLFloat8_e4m3fn = 10
    kDLFloat8_e4m3fnuz = 11
    kDLFloat8_e5m2 = 12
    kDLFloat8_e5m2fnuz = 13
    kDLFloat8_e8m0fnu = 14
    kDLFloat6_e2m3fn = 15
    kDLFloat6_e3m2fn = 16
    kDLFloat4_e2m1fn = 17


class mts_status_t(Enum):
    MTS_SUCCESS = 0
    MTS_INVALID_PARAMETER_ERROR = 1
    MTS_IO_ERROR = 2
    MTS_SERIALIZATION_ERROR = 3
    MTS_BUFFER_SIZE_ERROR = 4
    MTS_CALLBACK_ERROR = 254
    MTS_INTERNAL_ERROR = 255


class DLPackVersion(ctypes.Structure):
    pass


class DLDevice(ctypes.Structure):
    pass


class DLDataType(ctypes.Structure):
    pass


class DLTensor(ctypes.Structure):
    pass


class DLManagedTensor(ctypes.Structure):
    pass


class DLManagedTensorVersioned(ctypes.Structure):
    pass


class mts_block_t(ctypes.Structure):
    pass


class mts_labels_t(ctypes.Structure):
    pass


class mts_tensormap_t(ctypes.Structure):
    pass


class mts_data_movement_t(ctypes.Structure):
    pass


class mts_array_t(ctypes.Structure):
    pass


DLPackManagedTensorAllocator = CFUNCTYPE(ctypes.c_int, POINTER(DLTensor), POINTER(POINTER(DLManagedTensorVersioned)), ctypes.c_void_p, CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_char_p, ctypes.c_char_p))
DLPackManagedTensorFromPyObjectNoSync = CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, POINTER(POINTER(DLManagedTensorVersioned)))
DLPackDLTensorFromPyObjectNoSync = CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, POINTER(DLTensor))
DLPackCurrentWorkStream = CFUNCTYPE(ctypes.c_int, DLDeviceType, ctypes.c_int32, POINTER(POINTER(None)))
DLPackManagedTensorToPyObjectNoSync = CFUNCTYPE(ctypes.c_int, POINTER(DLManagedTensorVersioned), POINTER(POINTER(None)))
mts_data_origin_t = ctypes.c_uint64
mts_realloc_buffer_t = CFUNCTYPE(ctypes.c_char_p, ctypes.c_void_p, ctypes.c_char_p, c_uintptr_t)
mts_create_array_callback_t = CFUNCTYPE(mts_status_t, POINTER(c_uintptr_t), c_uintptr_t, DLDataType, POINTER(mts_array_t))


DLPackVersion._fields_ = [
    ("major", ctypes.c_uint32),
    ("minor", ctypes.c_uint32),
]

DLDevice._fields_ = [
    ("device_type", DLDeviceType),
    ("device_id", ctypes.c_int32),
]

DLDataType._fields_ = [
    ("code", ctypes.c_uint8),
    ("bits", ctypes.c_uint8),
    ("lanes", ctypes.c_uint16),
]

DLTensor._fields_ = [
    ("data", ctypes.c_void_p),
    ("device", DLDevice),
    ("ndim", ctypes.c_int32),
    ("dtype", DLDataType),
    ("shape", POINTER(ctypes.c_int64)),
    ("strides", POINTER(ctypes.c_int64)),
    ("byte_offset", ctypes.c_uint64),
]

DLManagedTensor._fields_ = [
    ("dl_tensor", DLTensor),
    ("manager_ctx", ctypes.c_void_p),
    ("deleter", CFUNCTYPE(None, POINTER(DLManagedTensor))),
]

DLManagedTensorVersioned._fields_ = [
    ("version", DLPackVersion),
    ("manager_ctx", ctypes.c_void_p),
    ("deleter", CFUNCTYPE(None, POINTER(DLManagedTensorVersioned))),
    ("flags", ctypes.c_uint64),
    ("dl_tensor", DLTensor),
]

mts_data_movement_t._fields_ = [
    ("sample_in", c_uintptr_t),
    ("sample_out", c_uintptr_t),
    ("properties_start_in", c_uintptr_t),
    ("properties_start_out", c_uintptr_t),
    ("properties_length", c_uintptr_t),
]

mts_array_t._fields_ = [
    ("ptr", ctypes.c_void_p),
    ("destroy", CFUNCTYPE(None, ctypes.c_void_p)),
    ("origin", CFUNCTYPE(mts_status_t, ctypes.c_void_p, POINTER(mts_data_origin_t))),
    ("device", CFUNCTYPE(mts_status_t, ctypes.c_void_p, POINTER(DLDevice))),
    ("dtype", CFUNCTYPE(mts_status_t, ctypes.c_void_p, POINTER(DLDataType))),
    ("as_dlpack", CFUNCTYPE(mts_status_t, ctypes.c_void_p, POINTER(POINTER(DLManagedTensorVersioned)), DLDevice, POINTER(ctypes.c_int64), DLPackVersion)),
    ("shape", CFUNCTYPE(mts_status_t, ctypes.c_void_p, POINTER(POINTER(c_uintptr_t)), POINTER(c_uintptr_t))),
    ("reshape", CFUNCTYPE(mts_status_t, ctypes.c_void_p, POINTER(c_uintptr_t), c_uintptr_t)),
    ("swap_axes", CFUNCTYPE(mts_status_t, ctypes.c_void_p, c_uintptr_t, c_uintptr_t)),
    ("create", CFUNCTYPE(mts_status_t, ctypes.c_void_p, POINTER(c_uintptr_t), c_uintptr_t, mts_array_t, POINTER(mts_array_t))),
    ("copy", CFUNCTYPE(mts_status_t, ctypes.c_void_p, POINTER(mts_array_t))),
    ("move_data", CFUNCTYPE(mts_status_t, ctypes.c_void_p, ctypes.c_void_p, POINTER(mts_data_movement_t), c_uintptr_t)),
]


def setup_functions(lib):
    from ._status import check_status

    lib.mts_disable_panic_printing.argtypes = [
    ]
    lib.mts_disable_panic_printing.restype = None

    lib.mts_version.argtypes = [
    ]
    lib.mts_version.restype = ctypes.c_char_p

    lib.mts_last_error.argtypes = [
        POINTER(ctypes.c_char_p),
        POINTER(ctypes.c_char_p),
        POINTER(POINTER(None)),
    ]
    lib.mts_last_error.restype = mts_status_t

    lib.mts_set_last_error.argtypes = [
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
        CFUNCTYPE(None, ctypes.c_void_p),
    ]
    lib.mts_set_last_error.restype = check_status

    lib.mts_labels.argtypes = [
        POINTER(ctypes.c_char_p),
        c_uintptr_t,
        mts_array_t,
    ]
    lib.mts_labels.restype = POINTER(mts_labels_t)

    lib.mts_labels_assume_unique.argtypes = [
        POINTER(ctypes.c_char_p),
        c_uintptr_t,
        mts_array_t,
    ]
    lib.mts_labels_assume_unique.restype = POINTER(mts_labels_t)

    lib.mts_labels_dimensions.argtypes = [
        POINTER(mts_labels_t),
        POINTER(POINTER(ctypes.c_char_p)),
        POINTER(c_uintptr_t),
    ]
    lib.mts_labels_dimensions.restype = check_status

    lib.mts_labels_values.argtypes = [
        POINTER(mts_labels_t),
        POINTER(mts_array_t),
    ]
    lib.mts_labels_values.restype = check_status

    lib.mts_labels_values_cpu.argtypes = [
        POINTER(mts_labels_t),
        POINTER(POINTER(ctypes.c_int32)),
        POINTER(c_uintptr_t),
        POINTER(c_uintptr_t),
    ]
    lib.mts_labels_values_cpu.restype = check_status

    lib.mts_labels_position.argtypes = [
        POINTER(mts_labels_t),
        POINTER(ctypes.c_int32),
        c_uintptr_t,
        POINTER(ctypes.c_int64),
    ]
    lib.mts_labels_position.restype = check_status

    lib.mts_labels_clone.argtypes = [
        POINTER(mts_labels_t),
    ]
    lib.mts_labels_clone.restype = POINTER(mts_labels_t)

    lib.mts_labels_union.argtypes = [
        POINTER(mts_labels_t),
        POINTER(mts_labels_t),
        POINTER(POINTER(mts_labels_t)),
        POINTER(ctypes.c_int64),
        c_uintptr_t,
        POINTER(ctypes.c_int64),
        c_uintptr_t,
    ]
    lib.mts_labels_union.restype = check_status

    lib.mts_labels_intersection.argtypes = [
        POINTER(mts_labels_t),
        POINTER(mts_labels_t),
        POINTER(POINTER(mts_labels_t)),
        POINTER(ctypes.c_int64),
        c_uintptr_t,
        POINTER(ctypes.c_int64),
        c_uintptr_t,
    ]
    lib.mts_labels_intersection.restype = check_status

    lib.mts_labels_difference.argtypes = [
        POINTER(mts_labels_t),
        POINTER(mts_labels_t),
        POINTER(POINTER(mts_labels_t)),
        POINTER(ctypes.c_int64),
        c_uintptr_t,
    ]
    lib.mts_labels_difference.restype = check_status

    lib.mts_labels_select.argtypes = [
        POINTER(mts_labels_t),
        POINTER(mts_labels_t),
        POINTER(ctypes.c_uint64),
        POINTER(c_uintptr_t),
    ]
    lib.mts_labels_select.restype = check_status

    lib.mts_labels_free.argtypes = [
        POINTER(mts_labels_t),
    ]
    lib.mts_labels_free.restype = check_status

    lib.mts_register_data_origin.argtypes = [
        ctypes.c_char_p,
        POINTER(mts_data_origin_t),
    ]
    lib.mts_register_data_origin.restype = check_status

    lib.mts_get_data_origin.argtypes = [
        mts_data_origin_t,
        ctypes.c_char_p,
        c_uintptr_t,
    ]
    lib.mts_get_data_origin.restype = check_status

    lib.mts_block.argtypes = [
        mts_array_t,
        POINTER(mts_labels_t),
        POINTER(POINTER(mts_labels_t)),
        c_uintptr_t,
        POINTER(mts_labels_t),
    ]
    lib.mts_block.restype = POINTER(mts_block_t)

    lib.mts_block_free.argtypes = [
        POINTER(mts_block_t),
    ]
    lib.mts_block_free.restype = check_status

    lib.mts_block_copy.argtypes = [
        POINTER(mts_block_t),
    ]
    lib.mts_block_copy.restype = POINTER(mts_block_t)

    lib.mts_block_labels.argtypes = [
        POINTER(mts_block_t),
        c_uintptr_t,
    ]
    lib.mts_block_labels.restype = POINTER(mts_labels_t)

    lib.mts_block_gradient.argtypes = [
        POINTER(mts_block_t),
        ctypes.c_char_p,
        POINTER(POINTER(mts_block_t)),
    ]
    lib.mts_block_gradient.restype = check_status

    lib.mts_block_data.argtypes = [
        POINTER(mts_block_t),
        POINTER(mts_array_t),
    ]
    lib.mts_block_data.restype = check_status

    lib.mts_block_add_gradient.argtypes = [
        POINTER(mts_block_t),
        ctypes.c_char_p,
        POINTER(mts_block_t),
    ]
    lib.mts_block_add_gradient.restype = check_status

    lib.mts_block_gradients_list.argtypes = [
        POINTER(mts_block_t),
        POINTER(POINTER(ctypes.c_char_p)),
        POINTER(c_uintptr_t),
    ]
    lib.mts_block_gradients_list.restype = check_status

    lib.mts_block_device.argtypes = [
        POINTER(mts_block_t),
        POINTER(DLDevice),
    ]
    lib.mts_block_device.restype = check_status

    lib.mts_block_dtype.argtypes = [
        POINTER(mts_block_t),
        POINTER(DLDataType),
    ]
    lib.mts_block_dtype.restype = check_status

    lib.mts_tensormap.argtypes = [
        POINTER(mts_labels_t),
        POINTER(POINTER(mts_block_t)),
        c_uintptr_t,
    ]
    lib.mts_tensormap.restype = POINTER(mts_tensormap_t)

    lib.mts_tensormap_free.argtypes = [
        POINTER(mts_tensormap_t),
    ]
    lib.mts_tensormap_free.restype = check_status

    lib.mts_tensormap_copy.argtypes = [
        POINTER(mts_tensormap_t),
    ]
    lib.mts_tensormap_copy.restype = POINTER(mts_tensormap_t)

    lib.mts_tensormap_keys.argtypes = [
        POINTER(mts_tensormap_t),
    ]
    lib.mts_tensormap_keys.restype = POINTER(mts_labels_t)

    lib.mts_tensormap_block_by_id.argtypes = [
        POINTER(mts_tensormap_t),
        POINTER(POINTER(mts_block_t)),
        c_uintptr_t,
    ]
    lib.mts_tensormap_block_by_id.restype = check_status

    lib.mts_tensormap_blocks_matching.argtypes = [
        POINTER(mts_tensormap_t),
        POINTER(c_uintptr_t),
        POINTER(c_uintptr_t),
        POINTER(mts_labels_t),
    ]
    lib.mts_tensormap_blocks_matching.restype = check_status

    lib.mts_tensormap_keys_to_properties.argtypes = [
        POINTER(mts_tensormap_t),
        POINTER(mts_labels_t),
        mts_array_t,
        ctypes.c_bool,
    ]
    lib.mts_tensormap_keys_to_properties.restype = POINTER(mts_tensormap_t)

    lib.mts_tensormap_components_to_properties.argtypes = [
        POINTER(mts_tensormap_t),
        POINTER(ctypes.c_char_p),
        c_uintptr_t,
    ]
    lib.mts_tensormap_components_to_properties.restype = POINTER(mts_tensormap_t)

    lib.mts_tensormap_keys_to_samples.argtypes = [
        POINTER(mts_tensormap_t),
        POINTER(mts_labels_t),
        mts_array_t,
        ctypes.c_bool,
    ]
    lib.mts_tensormap_keys_to_samples.restype = POINTER(mts_tensormap_t)

    lib.mts_tensormap_set_info.argtypes = [
        POINTER(mts_tensormap_t),
        ctypes.c_char_p,
        ctypes.c_char_p,
    ]
    lib.mts_tensormap_set_info.restype = check_status

    lib.mts_tensormap_get_info.argtypes = [
        POINTER(mts_tensormap_t),
        ctypes.c_char_p,
        POINTER(ctypes.c_char_p),
    ]
    lib.mts_tensormap_get_info.restype = check_status

    lib.mts_tensormap_info_keys.argtypes = [
        POINTER(mts_tensormap_t),
        POINTER(POINTER(ctypes.c_char_p)),
        POINTER(c_uintptr_t),
    ]
    lib.mts_tensormap_info_keys.restype = check_status

    lib.mts_tensormap_device.argtypes = [
        POINTER(mts_tensormap_t),
        POINTER(DLDevice),
    ]
    lib.mts_tensormap_device.restype = check_status

    lib.mts_tensormap_dtype.argtypes = [
        POINTER(mts_tensormap_t),
        POINTER(DLDataType),
    ]
    lib.mts_tensormap_dtype.restype = check_status

    lib.mts_labels_load.argtypes = [
        ctypes.c_char_p,
    ]
    lib.mts_labels_load.restype = POINTER(mts_labels_t)

    lib.mts_labels_load_buffer.argtypes = [
        ctypes.c_char_p,
        c_uintptr_t,
    ]
    lib.mts_labels_load_buffer.restype = POINTER(mts_labels_t)

    lib.mts_labels_save.argtypes = [
        ctypes.c_char_p,
        POINTER(mts_labels_t),
    ]
    lib.mts_labels_save.restype = check_status

    lib.mts_labels_save_buffer.argtypes = [
        POINTER(ctypes.c_char_p),
        POINTER(c_uintptr_t),
        ctypes.c_void_p,
        mts_realloc_buffer_t,
        POINTER(mts_labels_t),
    ]
    lib.mts_labels_save_buffer.restype = check_status

    lib.mts_block_load.argtypes = [
        ctypes.c_char_p,
        mts_create_array_callback_t,
    ]
    lib.mts_block_load.restype = POINTER(mts_block_t)

    lib.mts_block_load_buffer.argtypes = [
        ctypes.c_char_p,
        c_uintptr_t,
        mts_create_array_callback_t,
    ]
    lib.mts_block_load_buffer.restype = POINTER(mts_block_t)

    lib.mts_block_save.argtypes = [
        ctypes.c_char_p,
        POINTER(mts_block_t),
    ]
    lib.mts_block_save.restype = check_status

    lib.mts_block_save_buffer.argtypes = [
        POINTER(ctypes.c_char_p),
        POINTER(c_uintptr_t),
        ctypes.c_void_p,
        mts_realloc_buffer_t,
        POINTER(mts_block_t),
    ]
    lib.mts_block_save_buffer.restype = check_status

    lib.mts_tensormap_load.argtypes = [
        ctypes.c_char_p,
        mts_create_array_callback_t,
    ]
    lib.mts_tensormap_load.restype = POINTER(mts_tensormap_t)

    lib.mts_tensormap_load_buffer.argtypes = [
        ctypes.c_char_p,
        c_uintptr_t,
        mts_create_array_callback_t,
    ]
    lib.mts_tensormap_load_buffer.restype = POINTER(mts_tensormap_t)

    lib.mts_tensormap_save.argtypes = [
        ctypes.c_char_p,
        POINTER(mts_tensormap_t),
    ]
    lib.mts_tensormap_save.restype = check_status

    lib.mts_tensormap_save_buffer.argtypes = [
        POINTER(ctypes.c_char_p),
        POINTER(c_uintptr_t),
        ctypes.c_void_p,
        mts_realloc_buffer_t,
        POINTER(mts_tensormap_t),
    ]
    lib.mts_tensormap_save_buffer.restype = check_status
