[package]
name = "metatensor-torch"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.74"

[lib]
path = "lib.rs"

[dev-dependencies]
lazy_static = "1"
which = "7"

# home MSRV is now 1.81
home = "=0.5.9"
