@PACKAGE_INIT@

if(equistore_FOUND)
    return()
endif()

add_library(equistore SHARED IMPORTED GLOBAL)
set_target_properties(equistore PROPERTIES
    IMPORTED_LOCATION ${PACKAGE_PREFIX_DIR}/@LIB_INSTALL_DIR@/@EQUISTORE_LIB_NAME@
    INTERFACE_INCLUDE_DIRECTORIES ${PACKAGE_PREFIX_DIR}/@INCLUDE_INSTALL_DIR@/
)
